// Domain types that used to be generated by Prisma. They are hand-written now, and they
// are the API-facing (camelCase) shape — query files map snake_case rows onto these, so
// nothing above the query layer ever sees a database column name.
//
// Anything marked ⚠ is read by the live Android transmitter: see plan/07-api-contract.md.

export const ROLES = ["RIDER", "COMMISSAIRE"] as const;
export type Role = (typeof ROLES)[number];

export const AUTH_PROVIDER_TYPES = ["GOOGLE", "SMS", "EMAIL_PASSWORD"] as const;
export type AuthProviderType = (typeof AUTH_PROVIDER_TYPES)[number];

export const EVENT_TYPES = ["RIDE", "RACE"] as const;
export type EventType = (typeof EVENT_TYPES)[number];

export const EVENT_STATUSES = [
  "draft",
  "published",
  "registration_open",
  "ready",
  "live",
  "finished",
  "cancelled",
] as const;
export type EventStatus = (typeof EVENT_STATUSES)[number];

/**
 * Layer 5 of AUTHORIZATION.md — separate from roles and from plans.
 *   public      anyone, including a signed-out guest
 *   registered  any signed-in user
 *   private     only someone with a participation row or an event role; 404 to everyone else
 * Orthogonal to the six show_* flags, which say how MUCH a permitted viewer sees.
 */
export const EVENT_VISIBILITIES = ["public", "registered", "private"] as const;
export type EventVisibility = (typeof EVENT_VISIBILITIES)[number];

export const DISPLAY_MODES = ["standard", "competition"] as const;
export type DisplayMode = (typeof DISPLAY_MODES)[number];

export const REGISTRATION_STATUSES = [
  "registered",
  "waiting_approval",
  "approved",
  "rejected",
] as const;
export type RegistrationStatus = (typeof REGISTRATION_STATUSES)[number];

export const ATTENDANCE_STATUSES = ["unknown", "present", "dns", "started"] as const;
export type AttendanceStatus = (typeof ATTENDANCE_STATUSES)[number];

export const RESULT_STATUSES = ["none", "finished", "dnf", "stopped", "unknown"] as const;
export type ResultStatus = (typeof RESULT_STATUSES)[number];

/** What kind of riding an event is. Matches the client's SurfaceType picker. Distinct from
 *  EVENT_TYPES (RIDE | RACE), which is the frozen Android field. */
export const ACTIVITY_TYPES = ["road", "mtb", "gravel", "running", "hiking"] as const;
export type ActivityType = (typeof ACTIVITY_TYPES)[number];

/** One difficulty label for a whole ride — not per ride-group. */
export const RIDER_LEVELS = ["beginner", "intermediate", "masters", "elite", "world_tour"] as const;
export type RiderLevel = (typeof RIDER_LEVELS)[number];

export const ROUTE_TYPES = ["road", "gravel", "mtb", "mixed"] as const;
export type RouteType = (typeof ROUTE_TYPES)[number];

export const ROUTE_SOURCES = ["gpx", "tcx", "geojson", "json", "drawn", "copied"] as const;
export type RouteSource = (typeof ROUTE_SOURCES)[number];

export interface User {
  id: number;
  firstName: string | null;
  lastName: string | null;
  nickname: string | null;
  emergencyPhone: string | null;
  /** users.avatar_url — the Google profile picture, filled in at sign-up when Google
   *  supplied one. Never overwritten by a later login, and never overwritten by the
   *  avatar the rider chooses below either: it stays the fallback a reset returns to. */
  avatarUrl: string | null;
  /** The avatar the rider chose: "preset" with a registry id, "upload" with a relative
   *  reference under UPLOADS_DIR, or null for neither. See lib/user-images.ts for how these
   *  and avatarUrl combine into the single URL the API returns. */
  avatarType: string | null;
  avatarValue: string | null;
  /** The rider's wide cover image, same two shapes. There is no legacy fallback for a
   *  cover — unset simply means none. */
  coverType: string | null;
  coverValue: string | null;
  role: Role;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  lastLoginAt: Date | null;
}

export interface AuthIdentity {
  id: number;
  userId: number;
  provider: AuthProviderType;
  providerUserId: string;
  email: string | null;
  phone: string | null;
  passwordHash: string | null;
  verifiedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  lastUsedAt: Date | null;
}

export interface Session {
  id: number;
  userId: number;
  refreshTokenHash: string;
  createdAt: Date;
  expiresAt: Date;
  revokedAt: Date | null;
  lastUsedAt: Date | null;
  deviceInfo: string | null;
  ipAddress: string | null;
}

export interface Event {
  id: string;
  code: string; // ⚠ Android looks an event up by this
  name: string;
  type: EventType; // ⚠
  requiresBib: boolean; // ⚠
  startsAt: Date | null;
  endsAt: Date | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;

  ownerId: number | null;
  displayMode: DisplayMode;
  status: EventStatus;
  visibility: EventVisibility;
  description: string | null;
  location: string | null;
  area: string | null;
  finishedAt: Date | null;

  // Collected by the create form since long before the server could store any of them.
  activityType: ActivityType | null;
  level: RiderLevel | null;
  /** Free-text club name shown as "Organized by". Superseded by teamId when one is linked. */
  organizerGroup: string | null;
  /** Links this ride into a team's schedule. */
  teamId: number | null;
  requiresApproval: boolean; // self-join sets registration_status=waiting_approval instead of registered
  isPaused: boolean; // live display frozen; never affects location ingest — see event.service.ts

  /**
   * The organizer's authoritative elevation-gain value (metres), or null. Independent of any
   * attached route: it covers manual entry with no route and a corrected GPX import. Reads
   * expose the EFFECTIVE climb as COALESCE(this, attached route.elevation_m). See
   * sql/021-events-elevation-gain.sql.
   */
  elevationGainM: number | null;

  /**
   * Organizer-set ride plan — see sql/022-event-ride-plan.sql. None of these can be derived,
   * so they are stored, not computed.
   *   durationMin  expected ride time in whole minutes, or null when not stated
   *   restStops    number of rest / regroup stops (0 = none), or null when not stated
   *   isAccessible the organizer marked the ride suitable for riders who need assistance /
   *                adaptive equipment; defaults false
   */
  durationMin: number | null;
  restStops: number | null;
  isAccessible: boolean;

  /**
   * The organizer states a support / sag vehicle follows the ride — see
   * sql/024-event-support-vehicle.sql. Defaults false, and false means "not stated" as much as
   * it means "no": a rider must never plan around a vehicle nobody promised.
   */
  hasSupportVehicle: boolean;

  // What MAY OTHER PEOPLE see — per event, not per user. See plan/02-database-schema.md.
  showEventInfo: boolean;
  showParticipants: boolean;
  showRoute: boolean;
  showLiveLocations: boolean;
  showHistoryLocations: boolean;
  showResults: boolean;
}

export interface EventParticipant {
  id: number; // ⚠ this is `participantId` — the spine of the tracking system
  eventId: string;
  userId: number | null;
  bib: string | null; // ⚠ sent by Android on join
  joinedAt: Date;
  leftAt: Date | null;

  /** The row's own name (manual entry, Excel import) when set, otherwise the linked user's —
   *  resolved at read time by PARTICIPANT_DISPLAY_COLUMNS, not stored twice. */
  name: string | null;
  /** The linked user's `users.avatar_url`. Always null for a participant with no account. */
  avatarUrl: string | null;
  email: string | null;
  phone: string | null;
  category: string | null;
  /** Free text, shown on the results row. Not linked to the teams feature. */
  team: string | null;
  /** ISO 3166-1 alpha-2, stored uppercase. */
  countryCode: string | null;
  /** Which ride group they are in, if the organizer uses groups at all. */
  groupId: number | null;

  // THREE INDEPENDENT AXES — do not merge. See plan/02-database-schema.md.
  registrationStatus: RegistrationStatus;
  attendanceStatus: AttendanceStatus;
  resultStatus: ResultStatus;

  finishedAt: Date | null;
  finishPosition: number | null;
}

/**
 * 2-4 groups riding ONE event together, each optionally with its own start time and track.
 * Not a results concept: `category` is which class you are scored in, a group is who you ride
 * with. See sql/012-ride-groups.sql.
 */
export interface EventGroup {
  id: number;
  eventId: string;
  name: string;
  /** null means "starts with the event". */
  startsAt: Date | null;
  /** null means "uses the event's route". */
  routeId: number | null;
  sortOrder: number;
  createdAt: Date;
  updatedAt: Date;
}

export const TEAM_MEMBER_STATUSES = [
  "invited",
  "waiting_approval",
  "approved",
  "rejected",
] as const;
export type TeamMemberStatus = (typeof TEAM_MEMBER_STATUSES)[number];

/** A club. Its rides gather under one name, which a free-text organizer string cannot do. */
export interface Team {
  id: number;
  name: string;
  ownerId: number;
  avatarUrl: string | null;
  createdAt: Date;
  updatedAt: Date;
}

/** Mirrors EventParticipant: a member may have no account yet. */
export interface TeamMember {
  id: number;
  teamId: number;
  userId: number | null;
  /** Resolved at read time from the linked account when the row has no name of its own. */
  name: string | null;
  avatarUrl: string | null;
  email: string | null;
  phone: string | null;
  status: TeamMemberStatus;
  createdAt: Date;
}

/** A point on a route or a saved track. `ele` is present only when the source data had it. */
export interface TrackPoint {
  lat: number;
  lng: number;
  ele?: number | null;
}

export interface RouteMarker {
  lat: number;
  lng: number;
  label: string;
  type?: "start" | "finish" | "feed" | "point";
}

/**
 * Stored independently of any event so one route can serve many and be published to the
 * public library. Everything from distanceKm down is computed once, at creation — never on
 * read. See plan/08-routes-and-maps.md.
 */
export interface Route {
  id: number;
  ownerId: number | null;
  name: string | null;
  routeType: RouteType | null;
  source: RouteSource | null;
  distanceKm: number | null;
  elevationM: number | null;
  trackPoints: TrackPoint[] | null;
  markers: RouteMarker[] | null;
  /** Simplified geometry — what the public browser renders. Full geometry is trackPoints. */
  previewPoints: TrackPoint[] | null;
  pointCount: number | null;
  isPublic: boolean;
  placeName: string | null;
  startLat: number | null;
  startLon: number | null;
  endLat: number | null;
  endLon: number | null;
  bboxMinLat: number | null;
  bboxMinLon: number | null;
  bboxMaxLat: number | null;
  bboxMaxLon: number | null;
  createdAt: Date;
  updatedAt: Date;
}

/** A route attached to an event. Attaching copies nothing — this just points at the route. */
export interface EventRoute {
  id: number;
  eventId: string;
  routeId: number;
  createdAt: Date;
}

/**
 * Where one rider is *right now*. Upserted on every location batch; only a newer point may
 * overwrite. This is the only table the live map reads.
 */
export interface ParticipantLastLocation {
  eventId: string;
  participantId: number;
  recordedAt: Date | null;
  lat: number | null;
  lng: number | null;
  accuracy: number | null;
  emergency: boolean;
  distanceTravelledKm: number | null;
  updatedAt: Date;
}

/**
 * Written once, when an event finishes: one rider's ride reduced to a simplified line. Never
 * purged — this is what the History screen draws.
 */
export interface ParticipantTrack {
  id: number;
  eventId: string;
  participantId: number;
  points: TrackPoint[] | null;
  pointCount: number | null;
  distanceKm: number | null;
  startedAt: Date | null;
  endedAt: Date | null;
  hadEmergency: boolean;
  createdAt: Date;
}

export interface OtpChallenge {
  id: number;
  phone: string;
  codeHash: string;
  attemptCount: number;
  maxAttempts: number;
  createdAt: Date;
  expiresAt: Date;
  consumedAt: Date | null;
  requestIp: string | null;
}
