// Domain types that used to be generated by Prisma. They are hand-written now, and they
// are the API-facing (camelCase) shape — query files map snake_case rows onto these, so
// nothing above the query layer ever sees a database column name.
//
// Anything marked ⚠ is read by the live Android transmitter: see plan/07-api-contract.md.

export const ROLES = ["RIDER", "COMMISSAIRE"] as const;
export type Role = (typeof ROLES)[number];

export const AUTH_PROVIDER_TYPES = ["GOOGLE", "SMS", "EMAIL_PASSWORD"] as const;
export type AuthProviderType = (typeof AUTH_PROVIDER_TYPES)[number];

export const EVENT_TYPES = ["RIDE", "RACE"] as const;
export type EventType = (typeof EVENT_TYPES)[number];

export interface User {
  id: number;
  firstName: string | null;
  lastName: string | null;
  nickname: string | null;
  emergencyPhone: string | null;
  role: Role;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  lastLoginAt: Date | null;
}

export interface AuthIdentity {
  id: number;
  userId: number;
  provider: AuthProviderType;
  providerUserId: string;
  email: string | null;
  phone: string | null;
  passwordHash: string | null;
  verifiedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  lastUsedAt: Date | null;
}

export interface Session {
  id: number;
  userId: number;
  refreshTokenHash: string;
  createdAt: Date;
  expiresAt: Date;
  revokedAt: Date | null;
  lastUsedAt: Date | null;
  deviceInfo: string | null;
  ipAddress: string | null;
}

export interface Event {
  id: string;
  code: string; // ⚠ Android looks an event up by this
  name: string;
  type: EventType; // ⚠
  requiresBib: boolean; // ⚠
  startsAt: Date | null;
  endsAt: Date | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface EventParticipant {
  id: number; // ⚠ this is `participantId` — the spine of the tracking system
  eventId: string;
  userId: number | null;
  bib: string | null; // ⚠ sent by Android on join
  joinedAt: Date;
  leftAt: Date | null;
}

export interface OtpChallenge {
  id: number;
  phone: string;
  codeHash: string;
  attemptCount: number;
  maxAttempts: number;
  createdAt: Date;
  expiresAt: Date;
  consumedAt: Date | null;
  requestIp: string | null;
}
