-- seed.sql — intentionally empty.
--
-- Development seed data was removed: no mock events, users, riders or routes are inserted
-- by anything in this repo any more. Every row in a database now comes from a real request.
--
-- The file itself is kept because docker/postgres/Dockerfile COPYs it into
-- /docker-entrypoint-initdb.d/. An empty script runs cleanly, so a fresh container still
-- builds and starts — it just seeds nothing.
--
-- If you ever want throwaway data again, create it through the API rather than here, so it
-- goes through the same validation and authorization as real data.
